services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  ChriWo\Mailhandler\:
    resource: '../Classes/*'

  # Do not auto wire constructors of event classes
  ChriWo\Mailhandler\Event\BeforeMailSendEvent:
    autowire: false
